services:
  jenkins:
    # Cambiamos 'image' por 'build' para usar nuestro Dockerfile
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins_server
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    user: root # Mantenemos user:root para que tenga permisos sobre el socket
    networks:
      - jenkinsnet

volumes:
  jenkins_data:

networks:
  jenkinsnet:
    driver: bridge